### ISSUE TITLE
Making on/off change between icons.

### ISSUE THREAD

**Issue by shoddysheep** [VineshReddy/polybar-redshift#2]
Hello. :)
First off, thank you very much for doing the work on this script. 

I've been meaning to alter it a little bit, just in terms of the output in polybar. I've removed the prefix in the module inside my polybar config in exchange for having the lightbulb inside the script.
What I am trying to achieve is when it is on, it should be a solid lightbulb, and when it is off, it should be a regular one from the Awesome font: https://fontawesome.com/search?q=lightbulp&o=r&m=free

Here is my fonts inside my polybar config.

```
font-0 = monospace:size=11;2
font-1 = Font Awesome 6 Free,Font Awesome 6 Free Solid:style=Solid:size=13;4
font-2 = Font Awesome 6 Free,Font Awesome 6 Free Regular:style=Regular:size=13;4
```

No matter what I do, it only uses the Solid version. If I want it to use the Regular one, I have to remove the Solid one entirely. The part of the Redshift script for printf looks like this.

```
    case $REDSHIFT in
      on)
        printf ""
        ;;
      off)
        printf ""
        ;;

```

Is it possible to force a font inside the script and perhaps colour of the text, too? I have not been able to find any information that could fix it thus far. :( 

Besides this, it works as intended. :D

**Comment by VineshReddy** [comment]
Hey, thanks for reaching out. You made my day better :D

It's been a long back I have looked into this, If you want to change the color you can do it with an echo like 
      echo "%{F#FF4136}${REDSHIFT_TEMP}K%{F-}"

Other than what you said "If I want it to use the Regular one, I have to remove the Solid one entirely. "  or you can delete individual glyphs maybe. Try asking polybar team.

Thanks again :)

**Comment by shoddysheep** [comment]
Awwww, I'm glad to hear that. :)

Thank you very much for the colour fix. I'll try poking some polybar experts. Hope you're having a great weekend.
I'll close the door (topic) on my way out. :D
